### ISSUE TITLE
app error: undefined method 'queues' for Sidekiq

### ISSUE THREAD

**Issue by acrogenesis** [meskyanichi/hirefire-resource#26]
I get the error and I'm using the code on the documentation

```ruby
HireFire::Resource.configure do |config|
  config.dyno(:worker) do
    HireFire::Macro::Sidekiq.queue
  end
end

```

**Comment by meskyanichi** [comment]
Sidekiq had temporarily removed the `#queues` method in version `3.3.1`. However, they've re-added it in the latest release. Upgrading to the latest Sidekiq version should resolve your issue.

https://github.com/mperham/sidekiq/commit/e5b9f5e5d97de033695755c76d4d80f1dab8ab66

**Comment by acrogenesis** [comment]
I updated to 3.3.2 and the issue persisted, my quick fix is to use

```ruby
require 'sidekiq/api'
HireFire::Resource.configure do |config|
  config.dyno(:worker) do
    stats = Sidekiq::Stats.new
    stats.enqueued
  end
end

```

**Comment by acrogenesis** [comment]
That worked, thanks!

**Comment by meskyanichi** [comment]
No problem!
